Efficiently Insert Multiple Rows
Baeldung/sql-tutorials pull request #10
Opened 2024-05-16 23:56 UTC by amirsarb

2024-06-10 15:28 UTC, theangrydev approved these changes

2024-06-10 15:35 UTC, theangrydev requested changes

2024-06-10 15:35 UTC, theangrydev commented on SQL-Insert-Multiple-Rows/insert-multiple-rows.sql
> +FROM old_student
```suggestion
FROM Old_student
```

2024-06-13 13:02 UTC, theangrydev approved these changes

2024-06-26 23:09 UTC, amirsarb reviewed
Capital fixed.

2024-07-01 07:34 UTC, amirsarb commented
Folder changed

2024-07-05 21:01 UTC, theangrydev approved these changes

2024-07-11 06:34 UTC, amirsarb reviewed
### Note on Section 6 (Using UNION ALL)

The method described in Section 6 (Using UNION ALL) is PostgreSQL-specific. It is not supported in SQL Server and MySQL. 

Please review and confirm that this limitation is clearly communicated in the tutorial.

Thank you!

2024-07-22 09:41 UTC, amirsarb reviewed
change

2024-07-22 09:48 UTC, amirsarb reviewed
change

2024-07-22 09:49 UTC, closed without merging